"""add associationn table

Revision ID: 068b89ecfccd
Revises: 8a3700a4d2e8
Create Date: 2025-12-16 16:07:32.715247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068b89ecfccd'
down_revision: Union[str, Sequence[str], None] = '8a3700a4d2e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_projects_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uniq_users_projects_idx')
    )
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.add_column('projects', sa.Column('avatar', sa.String(), nullable=False))
    op.add_column('projects', sa.Column('files_dir', sa.String(), nullable=False))
    op.add_column('projects', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('projects', 'created_at')
    op.drop_column('projects', 'files_dir')
    op.drop_column('projects', 'avatar')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_table('user_projects_association')
    # ### end Alembic commands ###
